"use client";

import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import FinanceSubnav from "@/src/components/FinanceSubnav";
import { supabase } from "@/src/lib/supabase";
import { selectInitialProperty } from "@/src/lib/propertyScope";

type Property = { id: string; name: string; vat_rate: number };
type Category = { id: string; name: string };
type Expense = { id: string; expense_date: string; supplier_name: string; reference: string | null; description: string; payment_method: string; vat_amount: number; total_amount: number };
type Draft = { key: number; date: string; supplier: string; reference: string; description: string; method: string; categoryId: string; amount: string; vatIncluded: boolean };
const today = new Date().toISOString().slice(0, 10);
const emptyRow = (key: number): Draft => ({ key, date: today, supplier: "", reference: "", description: "", method: "eft", categoryId: "", amount: "", vatIncluded: true });
const money = new Intl.NumberFormat("en-NA", { style: "currency", currency: "NAD", minimumFractionDigits: 2 });

export default function ExpensesPage() {
  const [properties, setProperties] = useState<Property[]>([]); const [propertyId, setPropertyId] = useState(""); const [categories, setCategories] = useState<Category[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]);
  const [rows, setRows] = useState<Draft[]>(() => Array.from({ length: 6 }, (_, i) => emptyRow(i + 1))); const [nextKey, setNextKey] = useState(7);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [setupRequired, setSetupRequired] = useState(false); const [errorMessage, setErrorMessage] = useState(""); const [message, setMessage] = useState("");

  const loadExpenses = useCallback(async (selected: string) => { setLoading(true); setErrorMessage(""); setSetupRequired(false); const [c, e] = await Promise.all([supabase.from("expense_categories").select("id,name").eq("property_id", selected).eq("is_active", true).order("name"), supabase.from("expenses").select("id,expense_date,supplier_name,reference,description,payment_method,vat_amount,total_amount").eq("property_id", selected).neq("status", "reversed").order("expense_date", { ascending: false }).limit(100)]); if (c.error || e.error) { setSetupRequired(true); setErrorMessage(c.error?.message ?? e.error?.message ?? "Finance setup required."); } else { setCategories((c.data as Category[]) ?? []); setExpenses((e.data as Expense[]) ?? []); } setLoading(false); }, []);
  const initialise = useCallback(async () => { const { data, error } = await supabase.from("properties").select("id,name,vat_rate").eq("is_active", true).order("name"); if (error) { setErrorMessage(error.message); setLoading(false); return; } const { scoped, selected } = selectInitialProperty((data as Property[]) ?? []); setProperties(scoped); setPropertyId(selected); if (selected) await loadExpenses(selected); }, [loadExpenses]);
  useEffect(() => {
    // Initial client-side Supabase load; later refreshes are user-driven.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void initialise();
  }, [initialise]);
  const vatRate = Number(properties.find((p) => p.id === propertyId)?.vat_rate ?? 15);
  const usedRows = useMemo(() => rows.filter((row) => row.supplier.trim() || row.description.trim() || Number(row.amount) > 0), [rows]);
  const update = (key: number, values: Partial<Draft>) => setRows((current) => current.map((row) => row.key === key ? { ...row, ...values } : row));
  const addRow = () => { setRows((current) => [...current, emptyRow(nextKey)]); setNextKey((key) => key + 1); };

  async function saveBatch() {
    if (!usedRows.length) { setErrorMessage("Enter at least one expense row."); return; }
    if (usedRows.some((row) => !row.date || !row.supplier.trim() || !row.description.trim() || Number(row.amount) <= 0)) { setErrorMessage("Complete the date, supplier, description and amount on every used row."); return; }
    setSaving(true); setErrorMessage(""); setMessage("");
    const staff = JSON.parse(sessionStorage.getItem("netpos_staff") ?? "null") as { id?: string } | null;
    const records = usedRows.map((row) => { const amount = Number(row.amount); const vat = row.vatIncluded ? amount - amount / (1 + vatRate / 100) : amount * vatRate / 100; return { property_id: propertyId, expense_date: row.date, supplier_name: row.supplier.trim(), reference: row.reference.trim() || null, description: row.description.trim(), payment_method: row.method, category_id: row.categoryId || null, subtotal: round(row.vatIncluded ? amount - vat : amount), vat_amount: round(vat), total_amount: round(row.vatIncluded ? amount : amount + vat), created_by: staff?.id ?? null }; });
    const { error } = await supabase.from("expenses").insert(records);
    if (error) setErrorMessage(error.message); else { setMessage(`${records.length} expense${records.length === 1 ? "" : "s"} recorded successfully.`); setRows(Array.from({ length: 6 }, (_, i) => emptyRow(nextKey + i))); setNextKey((key) => key + 6); await loadExpenses(propertyId); }
    setSaving(false);
  }

  return <main style={page}><header style={header}><div><div style={eyebrow}>FINANCE · EXPENSE BATCH</div><h1 style={title}>Record expenses line by line</h1><p style={muted}>Enter a full supplier batch, check the total, then save all completed lines together.</p></div><select value={propertyId} onChange={(e) => { setPropertyId(e.target.value); void loadExpenses(e.target.value); }} style={propertySelect}>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></header>
  <FinanceSubnav />
  {setupRequired && <div style={warning}><strong>Finance database setup required.</strong><span>The finance tables could not be reached.</span></div>}{errorMessage && !setupRequired && <div style={errorBox}>{errorMessage}</div>}{message && <div style={success}>{message}</div>}
  <section style={panel}><div style={panelHead}><div><h2 style={panelTitle}>Expense batch</h2><p style={small}>Reference accepts a supplier invoice, receipt, EFT or other supporting number.</p></div><div style={batchSummary}><span>{usedRows.length} lines</span><strong>{money.format(usedRows.reduce((sum, row) => sum + (Number(row.amount) || 0), 0))}</strong></div></div>
    <div style={tableWrap}><table style={table}><thead><tr>{["Date","Supplier","Invoice / Reference","Description","Category","Method","Amount","VAT incl.",""].map((heading) => <th key={heading} style={th}>{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.key}><td style={td}><input aria-label={`Date row ${index + 1}`} type="date" value={row.date} onChange={(e) => update(row.key, { date: e.target.value })} style={cellControl} /></td><td style={td}><input aria-label={`Supplier row ${index + 1}`} value={row.supplier} onChange={(e) => update(row.key, { supplier: e.target.value })} placeholder="Supplier" style={cellControl} /></td><td style={td}><input aria-label={`Reference row ${index + 1}`} value={row.reference} onChange={(e) => update(row.key, { reference: e.target.value })} placeholder="INV / Receipt / EFT" style={cellControl} /></td><td style={td}><input aria-label={`Description row ${index + 1}`} value={row.description} onChange={(e) => update(row.key, { description: e.target.value })} placeholder="What was purchased?" style={wideControl} /></td><td style={td}><select aria-label={`Category row ${index + 1}`} value={row.categoryId} onChange={(e) => update(row.key, { categoryId: e.target.value })} style={cellControl}><option value="">Uncategorised</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td style={td}><select aria-label={`Method row ${index + 1}`} value={row.method} onChange={(e) => update(row.key, { method: e.target.value })} style={cellControl}><option value="eft">EFT</option><option value="cash">Cash</option><option value="card">Card</option><option value="account">Account</option></select></td><td style={td}><input aria-label={`Amount row ${index + 1}`} type="number" min="0.01" step="0.01" value={row.amount} onChange={(e) => update(row.key, { amount: e.target.value })} placeholder="0.00" style={amountControl} /></td><td style={{...td,textAlign:"center"}}><input aria-label={`VAT included row ${index + 1}`} type="checkbox" checked={row.vatIncluded} onChange={(e) => update(row.key, { vatIncluded: e.target.checked })} /></td><td style={td}><button type="button" aria-label={`Remove row ${index + 1}`} onClick={() => setRows((current) => current.length > 1 ? current.filter((item) => item.key !== row.key) : current)} style={remove}>×</button></td></tr>)}</tbody></table></div>
    <div style={footer}><button type="button" onClick={addRow} style={secondary}>+ Add row</button><span style={footerHint}>VAT is calculated at {vatRate}% per selected line.</span><button type="button" disabled={saving || setupRequired || !usedRows.length} onClick={() => void saveBatch()} style={primary}>{saving ? "Saving batch..." : `Save batch (${usedRows.length})`}</button></div>
  </section>
  <section style={{...panel,marginTop:14}}><div style={panelHead}><h2 style={panelTitle}>Recent recorded expenses</h2></div><div style={tableWrap}><table style={table}><thead><tr>{["Date","Supplier","Reference","Description","Method","VAT","Total"].map((heading) => <th key={heading} style={th}>{heading}</th>)}</tr></thead><tbody>{expenses.map((e) => <tr key={e.id}><td style={readTd}>{e.expense_date}</td><td style={readTd}><strong>{e.supplier_name}</strong></td><td style={readTd}>{e.reference || "—"}</td><td style={readTd}>{e.description}</td><td style={readTd}>{e.payment_method.toUpperCase()}</td><td style={{...readTd,textAlign:"right"}}>{money.format(Number(e.vat_amount))}</td><td style={{...readTd,textAlign:"right",fontWeight:800}}>{money.format(Number(e.total_amount))}</td></tr>)}{!loading && !expenses.length && <tr><td colSpan={7} style={empty}>No expenses recorded yet.</td></tr>}</tbody></table></div></section></main>;
}
function round(value: number) { return Math.round((value + Number.EPSILON) * 100) / 100; }
const page: CSSProperties = { minHeight: "calc(100vh - 112px)", padding: 24, background: "#F4F8FB", color: "#173F5F", fontFamily: "Arial,Helvetica,sans-serif" }; const header: CSSProperties = { maxWidth: 1440, margin: "0 auto 16px", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 20 }; const eyebrow: CSSProperties = { color: "#168257", fontSize: 12, fontWeight: 900, letterSpacing: 1.2 }; const title: CSSProperties = { margin: "6px 0", fontSize: 28, color: "#123F69" }; const muted: CSSProperties = { margin: 0, color: "#6C8293", fontSize: 14 }; const propertySelect: CSSProperties = { height: 42, minWidth: 230, padding: "0 11px", border: "1px solid #BDD0DE", borderRadius: 8, background: "#FFF", color: "#173F5F", fontWeight: 700 };
const warning: CSSProperties = { maxWidth: 1440, margin: "0 auto 14px", padding: 13, display: "flex", flexDirection: "column", gap: 4, border: "1px solid #E7C47C", borderRadius: 9, background: "#FFF8E8", color: "#77500D", fontSize: 13 }; const errorBox: CSSProperties = { ...warning, borderColor: "#E5B0B0", background: "#FFF2F2", color: "#982F2F" }; const success: CSSProperties = { ...warning, borderColor: "#A9D7BF", background: "#ECF8F1", color: "#176B49" };
const panel: CSSProperties = { maxWidth: 1440, margin: "0 auto", overflow: "hidden", border: "1px solid #D7E4ED", borderRadius: 11, background: "#FFF", boxShadow: "0 4px 14px rgba(18,63,105,.04)" }; const panelHead: CSSProperties = { padding: "14px 16px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, borderBottom: "1px solid #E5EDF3" }; const panelTitle: CSSProperties = { margin: 0, color: "#173F5F", fontSize: 17 }; const small: CSSProperties = { margin: "4px 0 0", color: "#708696", fontSize: 12 }; const batchSummary: CSSProperties = { display: "flex", alignItems: "center", gap: 14, color: "#607789", fontSize: 12 }; const tableWrap: CSSProperties = { overflowX: "auto" }; const table: CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: 12 }; const th: CSSProperties = { padding: "9px 8px", background: "#F4F8FB", color: "#607789", textAlign: "left", whiteSpace: "nowrap" }; const td: CSSProperties = { padding: 5, borderTop: "1px solid #E8EFF4", minWidth: 118 }; const readTd: CSSProperties = { padding: "11px 12px", borderTop: "1px solid #E8EFF4", color: "#526B7D", whiteSpace: "nowrap" }; const cellControl: CSSProperties = { width: "100%", minWidth: 115, height: 36, padding: "0 8px", boxSizing: "border-box", border: "1px solid #C3D4E0", borderRadius: 6, color: "#173F5F", fontSize: 12, background: "#FFF" }; const wideControl: CSSProperties = { ...cellControl, minWidth: 185 }; const amountControl: CSSProperties = { ...cellControl, minWidth: 90, textAlign: "right" }; const remove: CSSProperties = { width: 30, height: 30, border: 0, borderRadius: 6, background: "#FBECEC", color: "#A33A3A", fontSize: 18, cursor: "pointer" }; const footer: CSSProperties = { padding: 12, display: "flex", alignItems: "center", gap: 12, borderTop: "1px solid #E5EDF3" }; const footerHint: CSSProperties = { flex: 1, color: "#708696", fontSize: 12 }; const secondary: CSSProperties = { height: 38, padding: "0 13px", border: "1px solid #BDD0DE", borderRadius: 7, background: "#FFF", color: "#0D5FA8", fontWeight: 800, cursor: "pointer" }; const primary: CSSProperties = { height: 40, padding: "0 18px", border: 0, borderRadius: 7, background: "#168257", color: "#FFF", fontWeight: 900, cursor: "pointer" }; const empty: CSSProperties = { padding: 30, color: "#7B8F9E", textAlign: "center" };
