"use client";

import { useCallback, useEffect, useMemo, useState, type CSSProperties, type FormEvent } from "react";
import Link from "next/link";
import { supabase } from "@/src/lib/supabase";
import { selectInitialProperty } from "@/src/lib/propertyScope";

type Property = { id: string; name: string; vat_rate: number };
type Category = { id: string; name: string };
type Expense = { id: string; expense_date: string; supplier_name: string; reference: string | null; description: string; payment_method: string; subtotal: number; vat_amount: number; total_amount: number; status: string };
const money = new Intl.NumberFormat("en-NA", { style: "currency", currency: "NAD", minimumFractionDigits: 2 });

export default function ExpensesPage() {
  const [properties, setProperties] = useState<Property[]>([]); const [propertyId, setPropertyId] = useState(""); const [categories, setCategories] = useState<Category[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]);
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [supplier, setSupplier] = useState(""); const [reference, setReference] = useState(""); const [description, setDescription] = useState(""); const [method, setMethod] = useState("eft"); const [categoryId, setCategoryId] = useState(""); const [total, setTotal] = useState(""); const [vatIncluded, setVatIncluded] = useState(true);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [setupRequired, setSetupRequired] = useState(false); const [errorMessage, setErrorMessage] = useState(""); const [message, setMessage] = useState("");

  const loadExpenses = useCallback(async (selected: string) => { setLoading(true); setErrorMessage(""); setSetupRequired(false); const [c, e] = await Promise.all([supabase.from("expense_categories").select("id,name").eq("property_id", selected).eq("is_active", true).order("name"), supabase.from("expenses").select("id,expense_date,supplier_name,reference,description,payment_method,subtotal,vat_amount,total_amount,status").eq("property_id", selected).neq("status", "reversed").order("expense_date", { ascending: false }).limit(100)]); if (c.error || e.error) { setSetupRequired(true); setErrorMessage(c.error?.message ?? e.error?.message ?? "Finance setup required."); } else { setCategories((c.data as Category[]) ?? []); setExpenses((e.data as Expense[]) ?? []); } setLoading(false); }, []);
  const initialise = useCallback(async () => { const { data, error } = await supabase.from("properties").select("id,name,vat_rate").eq("is_active", true).order("name"); if (error) { setErrorMessage(error.message); setLoading(false); return; } const { scoped, selected } = selectInitialProperty((data as Property[]) ?? []); setProperties(scoped); setPropertyId(selected); if (selected) await loadExpenses(selected); }, [loadExpenses]);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void initialise();
  }, [initialise]);
  const vatRate = Number(properties.find((p) => p.id === propertyId)?.vat_rate ?? 15); const amounts = useMemo(() => { const gross = Math.max(0, Number(total) || 0); const vat = vatIncluded ? gross - gross / (1 + vatRate / 100) : gross * vatRate / 100; return { subtotal: vatIncluded ? gross - vat : gross, vat, gross: vatIncluded ? gross : gross + vat }; }, [total, vatIncluded, vatRate]);

  async function save(event: FormEvent) { event.preventDefault(); if (!propertyId || !supplier.trim() || !description.trim() || amounts.gross <= 0) { setErrorMessage("Enter the supplier, description and a valid amount."); return; } setSaving(true); setErrorMessage(""); setMessage(""); const staff = JSON.parse(sessionStorage.getItem("netpos_staff") ?? "null") as { id?: string } | null; const { error } = await supabase.from("expenses").insert({ property_id: propertyId, expense_date: date, supplier_name: supplier.trim(), reference: reference.trim() || null, description: description.trim(), payment_method: method, category_id: categoryId || null, subtotal: round(amounts.subtotal), vat_amount: round(amounts.vat), total_amount: round(amounts.gross), created_by: staff?.id ?? null }); if (error) setErrorMessage(error.message); else { setMessage("Expense recorded successfully."); setSupplier(""); setReference(""); setDescription(""); setTotal(""); await loadExpenses(propertyId); } setSaving(false); }

  return <main style={page}><header style={header}><div><div style={eyebrow}>FINANCE · EXPENSES</div><h1 style={title}>Record operating expenses</h1><p style={muted}>Capture supplier costs and VAT so cashbook and bank figures remain complete.</p></div><div style={actions}><Link href="/finance/cashbook" style={secondary}>← Cashbook</Link><select value={propertyId} onChange={(e) => { setPropertyId(e.target.value); void loadExpenses(e.target.value); }} style={select}>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div></header>
  {setupRequired && <div style={warning}><strong>Finance database setup required.</strong><span>Apply migration 002 before recording expenses.</span></div>}{errorMessage && !setupRequired && <div style={errorBox}>{errorMessage}</div>}{message && <div style={success}>{message}</div>}
  <section style={grid}><form onSubmit={save} style={form}><h2 style={panelTitle}>New expense</h2><div style={two}><label style={field}>Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} style={control} /></label><label style={field}>Payment method<select value={method} onChange={(e) => setMethod(e.target.value)} style={control}><option value="eft">EFT</option><option value="cash">Cash</option><option value="card">Card</option><option value="account">Account</option></select></label></div><label style={field}>Supplier<input value={supplier} onChange={(e) => setSupplier(e.target.value)} style={control} placeholder="Supplier or payee" /></label><label style={field}>Description<input value={description} onChange={(e) => setDescription(e.target.value)} style={control} placeholder="What was purchased?" /></label><div style={two}><label style={field}>Reference<input value={reference} onChange={(e) => setReference(e.target.value)} style={control} placeholder="Invoice / EFT reference" /></label><label style={field}>Category<select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} style={control}><option value="">Uncategorised</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label style={field}>Amount<input type="number" min="0.01" step="0.01" value={total} onChange={(e) => setTotal(e.target.value)} style={control} /></label><label style={check}><input type="checkbox" checked={vatIncluded} onChange={(e) => setVatIncluded(e.target.checked)} /> Amount includes VAT ({vatRate}%)</label><div style={breakdown}><span>Subtotal <strong>{money.format(amounts.subtotal)}</strong></span><span>VAT <strong>{money.format(amounts.vat)}</strong></span><span>Total <strong>{money.format(amounts.gross)}</strong></span></div><button disabled={saving || setupRequired} style={primary}>{saving ? "Saving..." : "Record Expense"}</button></form>
  <div style={panel}><h2 style={{...panelTitle, padding: 17}}>Recent expenses</h2><div style={list}>{expenses.map((e) => <div key={e.id} style={row}><div><strong style={rowTitle}>{e.supplier_name}</strong><span style={rowMeta}>{new Date(`${e.expense_date}T12:00:00`).toLocaleDateString("en-NA")} · {e.description} · {e.payment_method.toUpperCase()}</span></div><strong style={rowAmount}>{money.format(Number(e.total_amount))}</strong></div>)}{!loading && expenses.length === 0 && <div style={empty}>No expenses recorded yet.</div>}</div></div></section></main>;
}
function round(value: number) { return Math.round((value + Number.EPSILON) * 100) / 100; }
const page: CSSProperties = { minHeight: "calc(100vh - 112px)", padding: 24, background: "#F4F8FB", color: "#173F5F", fontFamily: "Arial,Helvetica,sans-serif" }; const header: CSSProperties = { maxWidth: 1300, margin: "0 auto 18px", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 20 }; const eyebrow: CSSProperties = { color: "#168257", fontSize: 12, fontWeight: 900, letterSpacing: 1.2 }; const title: CSSProperties = { margin: "6px 0", fontSize: 28, color: "#123F69" }; const muted: CSSProperties = { margin: 0, color: "#6C8293", fontSize: 14 }; const actions: CSSProperties = { display: "flex", gap: 9 }; const secondary: CSSProperties = { padding: "12px 13px", border: "1px solid #BDD0DE", borderRadius: 8, background: "#FFF", color: "#0D5FA8", textDecoration: "none", fontSize: 13, fontWeight: 800 }; const select: CSSProperties = { height: 42, minWidth: 210, padding: "0 11px", border: "1px solid #BDD0DE", borderRadius: 8, background: "#FFF", color: "#173F5F", fontWeight: 700 };
const warning: CSSProperties = { maxWidth: 1300, margin: "0 auto 14px", padding: 13, display: "flex", flexDirection: "column", gap: 4, border: "1px solid #E7C47C", borderRadius: 9, background: "#FFF8E8", color: "#77500D", fontSize: 13 }; const errorBox: CSSProperties = { ...warning, borderColor: "#E5B0B0", background: "#FFF2F2", color: "#982F2F" }; const success: CSSProperties = { ...warning, borderColor: "#A9D7BF", background: "#ECF8F1", color: "#176B49" };
const grid: CSSProperties = { maxWidth: 1300, margin: "0 auto", display: "grid", gridTemplateColumns: "minmax(380px,.85fr) minmax(440px,1.15fr)", gap: 14 }; const form: CSSProperties = { padding: 18, border: "1px solid #D7E4ED", borderRadius: 11, background: "#FFF" }; const panel: CSSProperties = { border: "1px solid #D7E4ED", borderRadius: 11, background: "#FFF", overflow: "hidden" }; const panelTitle: CSSProperties = { margin: 0, color: "#173F5F", fontSize: 17 }; const two: CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }; const field: CSSProperties = { display: "flex", flexDirection: "column", gap: 5, marginTop: 13, color: "#526B7D", fontSize: 12, fontWeight: 800 }; const control: CSSProperties = { width: "100%", height: 41, padding: "0 10px", border: "1px solid #BFD1DF", borderRadius: 8, color: "#173F5F", fontSize: 13, boxSizing: "border-box" }; const check: CSSProperties = { display: "flex", alignItems: "center", gap: 8, marginTop: 14, color: "#526B7D", fontSize: 12, fontWeight: 700 }; const breakdown: CSSProperties = { margin: "14px 0", padding: 11, display: "grid", gap: 7, borderRadius: 8, background: "#F2F7FA", color: "#607789", fontSize: 12 }; const primary: CSSProperties = { width: "100%", height: 43, border: 0, borderRadius: 8, background: "#168257", color: "#FFF", fontSize: 14, fontWeight: 900, cursor: "pointer" }; const list: CSSProperties = { maxHeight: "calc(100vh - 300px)", overflow: "auto" }; const row: CSSProperties = { padding: "13px 17px", display: "flex", justifyContent: "space-between", gap: 15, borderTop: "1px solid #E7EEF3" }; const rowTitle: CSSProperties = { display: "block", color: "#164D79", fontSize: 13 }; const rowMeta: CSSProperties = { display: "block", marginTop: 5, color: "#718697", fontSize: 11 }; const rowAmount: CSSProperties = { color: "#A33A3A", fontSize: 14, whiteSpace: "nowrap" }; const empty: CSSProperties = { padding: 30, color: "#7B8F9E", textAlign: "center" };
