"use client";

import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import FinanceSubnav from "@/src/components/FinanceSubnav";
import { supabase } from "@/src/lib/supabase";
import { selectInitialProperty } from "@/src/lib/propertyScope";
type Property={id:string;name:string;vat_rate:number};type Invoice={id:string;invoice_date:string;invoice_number:string;status:string;subtotal:number;vat_amount:number;total_amount:number};type Expense={id:string;expense_date:string;supplier_name:string;reference:string|null;subtotal:number;vat_amount:number;total_amount:number};
const money=new Intl.NumberFormat("en-NA",{style:"currency",currency:"NAD",minimumFractionDigits:2});
export default function VatReportPage(){const [properties,setProperties]=useState<Property[]>([]);const [propertyId,setPropertyId]=useState("");const [from,setFrom]=useState(`${new Date().toISOString().slice(0,7)}-01`);const [to,setTo]=useState(new Date().toISOString().slice(0,10));const [invoices,setInvoices]=useState<Invoice[]>([]);const [expenses,setExpenses]=useState<Expense[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
const load=useCallback(async(property:string)=>{setLoading(true);setError("");const [i,e]=await Promise.all([supabase.from("invoices").select("id,invoice_date,invoice_number,status,subtotal,vat_amount,total_amount").eq("property_id",property).gte("invoice_date",from).lte("invoice_date",to).neq("status","void").order("invoice_date"),supabase.from("expenses").select("id,expense_date,supplier_name,reference,subtotal,vat_amount,total_amount").eq("property_id",property).gte("expense_date",from).lte("expense_date",to).eq("status","posted").order("expense_date")]);if(i.error||e.error)setError(i.error?.message??e.error?.message??"Could not load VAT report.");else{setInvoices((i.data as Invoice[])??[]);setExpenses((e.data as Expense[])??[]);}setLoading(false);},[from,to]);const initialise=useCallback(async()=>{const r=await supabase.from("properties").select("id,name,vat_rate").eq("is_active",true).order("name");if(r.error){setError(r.error.message);setLoading(false);return;}const {scoped,selected}=selectInitialProperty((r.data as Property[])??[]);setProperties(scoped);setPropertyId(selected);if(selected)await load(selected);},[load]);useEffect(()=>{
// eslint-disable-next-line react-hooks/set-state-in-effect
void initialise();
},[initialise]);
const totals=useMemo(()=>{const output=invoices.reduce((s,x)=>s+Number(x.vat_amount),0);const input=expenses.reduce((s,x)=>s+Number(x.vat_amount),0);return{sales:invoices.reduce((s,x)=>s+Number(x.total_amount),0),purchases:expenses.reduce((s,x)=>s+Number(x.total_amount),0),output,input,payable:output-input};},[invoices,expenses]);
return <main style={page}><header style={header}><div><div style={eyebrow}>FINANCE · VAT REPORT</div><h1 style={title}>VAT report</h1><p style={muted}>Output VAT from invoices less input VAT from recorded operating expenses.</p></div><select value={propertyId} onChange={e=>{setPropertyId(e.target.value);void load(e.target.value);}} style={control}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></header><FinanceSubnav />{error&&<div style={errorBox}>{error}</div>}<section style={filters}><label style={field}>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={control}/></label><label style={field}>To<input type="date" value={to} onChange={e=>setTo(e.target.value)} style={control}/></label><button onClick={()=>void load(propertyId)} style={primary}>Run VAT report</button><span style={note}>VAT rate: {properties.find(p=>p.id===propertyId)?.vat_rate??15}%</span></section><section style={cards}><Card label="Taxable sales (gross)" value={money.format(totals.sales)}/><Card label="Output VAT" value={money.format(totals.output)}/><Card label="Input VAT" value={money.format(totals.input)}/><Card label={totals.payable>=0?"VAT payable":"VAT credit"} value={money.format(Math.abs(totals.payable))} strong/></section>
<section style={grid}><VatTable title="Sales / Output VAT" empty="No non-void invoices in this period." rows={invoices.map(x=>({id:x.id,date:x.invoice_date,name:x.invoice_number,reference:x.status.toUpperCase(),subtotal:x.subtotal,vat:x.vat_amount,total:x.total_amount}))} loading={loading}/><VatTable title="Purchases / Input VAT" empty="No posted expenses in this period." rows={expenses.map(x=>({id:x.id,date:x.expense_date,name:x.supplier_name,reference:x.reference||"—",subtotal:x.subtotal,vat:x.vat_amount,total:x.total_amount}))} loading={loading}/></section><p style={disclaimer}>Control report for review. Confirm claimable input VAT and filing treatment with the property’s accountant before submitting a VAT return.</p></main>}
function Card({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div style={{...card,...(strong?strongCard:{})}}><span>{label}</span><strong>{value}</strong></div>}function VatTable({title,rows,empty,loading}:{title:string;rows:Array<{id:string;date:string;name:string;reference:string;subtotal:number;vat:number;total:number}>;empty:string;loading:boolean}){return <section style={panel}><h2 style={panelTitle}>{title}</h2><div style={{overflowX:"auto"}}><table style={table}><thead><tr>{["Date","Document / Supplier","Reference","Excl. VAT","VAT","Incl. VAT"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td style={td}>{x.date}</td><td style={td}><strong>{x.name}</strong></td><td style={td}>{x.reference}</td><td style={{...td,textAlign:"right"}}>{money.format(Number(x.subtotal))}</td><td style={{...td,textAlign:"right"}}>{money.format(Number(x.vat))}</td><td style={{...td,textAlign:"right",fontWeight:800}}>{money.format(Number(x.total))}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={6} style={emptyCell}>{empty}</td></tr>}</tbody></table></div></section>}
const page:CSSProperties={minHeight:"calc(100vh - 112px)",padding:24,background:"#F4F8FB",color:"#173F5F",fontFamily:"Arial,Helvetica,sans-serif"};const header:CSSProperties={maxWidth:1440,margin:"0 auto 16px",display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:20};const eyebrow:CSSProperties={color:"#168257",fontSize:12,fontWeight:900,letterSpacing:1.2};const title:CSSProperties={margin:"6px 0",fontSize:28,color:"#123F69"};const muted:CSSProperties={margin:0,color:"#6C8293",fontSize:14};const filters:CSSProperties={maxWidth:1440,margin:"0 auto 12px",padding:12,display:"flex",alignItems:"flex-end",gap:10,border:"1px solid #D7E4ED",borderRadius:10,background:"#FFF"};const field:CSSProperties={display:"flex",flexDirection:"column",gap:5,color:"#607789",fontSize:11,fontWeight:800};const control:CSSProperties={height:39,minWidth:180,padding:"0 10px",border:"1px solid #BDD0DE",borderRadius:7,background:"#FFF",color:"#173F5F",fontWeight:700};const primary:CSSProperties={height:39,padding:"0 15px",border:0,borderRadius:7,background:"#0D5FA8",color:"#FFF",fontWeight:800,cursor:"pointer"};const note:CSSProperties={marginLeft:"auto",color:"#607789",fontSize:12};const cards:CSSProperties={maxWidth:1440,margin:"0 auto 12px",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10};const card:CSSProperties={padding:15,display:"flex",flexDirection:"column",gap:8,border:"1px solid #D7E4ED",borderRadius:9,background:"#FFF",color:"#607789",fontSize:12};const strongCard:CSSProperties={borderColor:"#86C2A5",background:"#EEF8F3",color:"#176B49"};const grid:CSSProperties={maxWidth:1440,margin:"0 auto",display:"grid",gridTemplateColumns:"1fr 1fr",gap:12};const panel:CSSProperties={minWidth:0,overflow:"hidden",border:"1px solid #D7E4ED",borderRadius:10,background:"#FFF"};const panelTitle:CSSProperties={margin:0,padding:14,color:"#173F5F",fontSize:16};const table:CSSProperties={width:"100%",borderCollapse:"collapse",fontSize:11};const th:CSSProperties={padding:"9px 10px",background:"#F4F8FB",color:"#607789",textAlign:"left",whiteSpace:"nowrap"};const td:CSSProperties={padding:"10px",borderTop:"1px solid #E6EEF3",color:"#526B7D",whiteSpace:"nowrap"};const errorBox:CSSProperties={maxWidth:1440,margin:"0 auto 12px",padding:12,border:"1px solid #E5B0B0",borderRadius:8,background:"#FFF2F2",color:"#982F2F"};const emptyCell:CSSProperties={padding:30,textAlign:"center",color:"#788D9C"};const disclaimer:CSSProperties={maxWidth:1440,margin:"12px auto 0",color:"#718697",fontSize:11};
