"use client";

import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import FinanceSubnav from "@/src/components/FinanceSubnav";
import { supabase } from "@/src/lib/supabase";
import { selectInitialProperty } from "@/src/lib/propertyScope";

type Property = { id: string; name: string }; type Account = { id: string; account_name: string; bank_name: string }; type Line = { id: string; transaction_date: string; description: string; bank_reference: string | null; amount: number; balance: number | null; match_status: string };
const money = new Intl.NumberFormat("en-NA", { style: "currency", currency: "NAD", minimumFractionDigits: 2 });
export default function BankStatementPage() {
  const [properties,setProperties]=useState<Property[]>([]); const [propertyId,setPropertyId]=useState(""); const [accounts,setAccounts]=useState<Account[]>([]); const [accountId,setAccountId]=useState(""); const [lines,setLines]=useState<Line[]>([]); const [from,setFrom]=useState(`${new Date().toISOString().slice(0,7)}-01`); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const loadLines=useCallback(async(property:string,account?:string)=>{setLoading(true);setError("");const ar=await supabase.from("bank_accounts").select("id,account_name,bank_name").eq("property_id",property).eq("is_active",true).order("account_name");if(ar.error){setError(ar.error.message);setLoading(false);return;}const aa=(ar.data as Account[])??[];const chosen=aa.some(x=>x.id===account)?account!:aa[0]?.id??"";setAccounts(aa);setAccountId(chosen);if(!chosen){setLines([]);setLoading(false);return;}const lr=await supabase.from("bank_statement_lines").select("id,transaction_date,description,bank_reference,amount,balance,match_status").eq("bank_account_id",chosen).gte("transaction_date",from).lte("transaction_date",to).order("transaction_date",{ascending:true});if(lr.error)setError(lr.error.message);else setLines((lr.data as Line[])??[]);setLoading(false);},[from,to]);
  const initialise=useCallback(async()=>{const r=await supabase.from("properties").select("id,name").eq("is_active",true).order("name");if(r.error){setError(r.error.message);setLoading(false);return;}const {scoped,selected}=selectInitialProperty((r.data as Property[])??[]);setProperties(scoped);setPropertyId(selected);if(selected)await loadLines(selected);},[loadLines]); useEffect(()=>{
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void initialise();
  },[initialise]);
  const totals=useMemo(()=>({moneyIn:lines.filter(x=>Number(x.amount)>0).reduce((s,x)=>s+Number(x.amount),0),moneyOut:lines.filter(x=>Number(x.amount)<0).reduce((s,x)=>s+Math.abs(Number(x.amount)),0),unmatched:lines.filter(x=>x.match_status==="unmatched"||x.match_status==="suggested").length}),[lines]);
  return <main style={page}><header style={header}><div><div style={eyebrow}>FINANCE · BANK STATEMENT</div><h1 style={title}>Bank statement</h1><p style={muted}>A clear line-by-line record of imported bank transactions and their matching status.</p></div><select value={propertyId} onChange={e=>{setPropertyId(e.target.value);void loadLines(e.target.value);}} style={control}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></header><FinanceSubnav />{error&&<div style={errorBox}>{error}</div>}
  <section style={filters}><label style={field}>Bank account<select value={accountId} onChange={e=>{setAccountId(e.target.value);void loadLines(propertyId,e.target.value);}} style={control}>{accounts.map(a=><option key={a.id} value={a.id}>{a.bank_name} · {a.account_name}</option>)}</select></label><label style={field}>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={control}/></label><label style={field}>To<input type="date" value={to} onChange={e=>setTo(e.target.value)} style={control}/></label><button onClick={()=>void loadLines(propertyId,accountId)} style={primary}>Refresh</button><a href="/finance/bank-reconciliation" style={linkButton}>Import / Reconcile</a></section>
  <section style={summary}><Card label="Money in" value={money.format(totals.moneyIn)}/><Card label="Money out" value={money.format(totals.moneyOut)}/><Card label="Unmatched lines" value={String(totals.unmatched)}/><Card label="Statement lines" value={String(lines.length)}/></section>
  <section style={panel}><table style={table}><thead><tr>{["Date","Bank description","Reference","Status","Debit","Credit","Balance"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{lines.map(x=><tr key={x.id}><td style={td}>{x.transaction_date}</td><td style={td}>{x.description}</td><td style={td}>{x.bank_reference||"—"}</td><td style={td}><span style={{...badge,background:x.match_status==="matched"?"#E7F6EE":"#FFF3DD",color:x.match_status==="matched"?"#16704B":"#8A5A0A"}}>{x.match_status.toUpperCase()}</span></td><td style={{...td,textAlign:"right"}}>{Number(x.amount)<0?money.format(Math.abs(Number(x.amount))):"—"}</td><td style={{...td,textAlign:"right"}}>{Number(x.amount)>0?money.format(Number(x.amount)):"—"}</td><td style={{...td,textAlign:"right",fontWeight:800}}>{x.balance==null?"—":money.format(Number(x.balance))}</td></tr>)}{!loading&&!lines.length&&<tr><td colSpan={7} style={empty}>No bank statement lines for this period. Import a CSV under Bank Reconciliation.</td></tr>}</tbody></table></section></main>;
}
function Card({label,value}:{label:string;value:string}){return <div style={card}><span>{label}</span><strong>{value}</strong></div>}
const page:CSSProperties={minHeight:"calc(100vh - 112px)",padding:24,background:"#F4F8FB",color:"#173F5F",fontFamily:"Arial,Helvetica,sans-serif"};const header:CSSProperties={maxWidth:1440,margin:"0 auto 16px",display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:20};const eyebrow:CSSProperties={color:"#168257",fontSize:12,fontWeight:900,letterSpacing:1.2};const title:CSSProperties={margin:"6px 0",fontSize:28,color:"#123F69"};const muted:CSSProperties={margin:0,color:"#6C8293",fontSize:14};const filters:CSSProperties={maxWidth:1440,margin:"0 auto 12px",padding:12,display:"flex",alignItems:"flex-end",gap:10,border:"1px solid #D7E4ED",borderRadius:10,background:"#FFF"};const field:CSSProperties={display:"flex",flexDirection:"column",gap:5,color:"#607789",fontSize:11,fontWeight:800};const control:CSSProperties={height:39,minWidth:170,padding:"0 10px",border:"1px solid #BDD0DE",borderRadius:7,background:"#FFF",color:"#173F5F",fontWeight:700};const primary:CSSProperties={height:39,padding:"0 15px",border:0,borderRadius:7,background:"#0D5FA8",color:"#FFF",fontWeight:800,cursor:"pointer"};const linkButton:CSSProperties={...primary,display:"grid",placeItems:"center",textDecoration:"none",background:"#168257"};const summary:CSSProperties={maxWidth:1440,margin:"0 auto 12px",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10};const card:CSSProperties={padding:14,display:"flex",justifyContent:"space-between",border:"1px solid #D7E4ED",borderRadius:9,background:"#FFF",color:"#607789",fontSize:12};const panel:CSSProperties={maxWidth:1440,margin:"0 auto",overflowX:"auto",border:"1px solid #D7E4ED",borderRadius:10,background:"#FFF"};const table:CSSProperties={width:"100%",borderCollapse:"collapse",fontSize:12};const th:CSSProperties={padding:"10px 12px",background:"#F4F8FB",color:"#607789",textAlign:"left"};const td:CSSProperties={padding:"11px 12px",borderTop:"1px solid #E6EEF3",color:"#526B7D",whiteSpace:"nowrap"};const badge:CSSProperties={padding:"4px 7px",borderRadius:999,fontSize:10,fontWeight:900};const errorBox:CSSProperties={maxWidth:1440,margin:"0 auto 12px",padding:12,border:"1px solid #E5B0B0",borderRadius:8,background:"#FFF2F2",color:"#982F2F"};const empty:CSSProperties={padding:34,textAlign:"center",color:"#788D9C"};
